# GameVault ??????
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# ?????
spring:
  application:
    name: gamevault-backend

  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gamevault?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  # JPA/Hibernate ??
  jpa:
    hibernate:
      ddl-auto: validate  # ??????????????
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  # ??????
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 2KB

  # Redis ????????
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

# MyBatis ??
mybatis:
  configuration:
    map-underscore-to-camel-case: true  # ??snake_case?camelCase??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # ??SQL??

# ????
logging:
  level:
    com.example.springboot: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.example.springboot.mapper: DEBUG  # ??MyBatis SQL??
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/gamevault.log

# JWT ??
jwt:
  secret: gamevault-secret-key-2024-very-long-and-secure-for-hs512-algorithm-minimum-512-bits-required
  expiration: 86400000  # 24??????
  refresh-expiration: 604800000  # 7?????

# ??????
file:
  upload:
    path: ./uploads/
    max-size: 104857600  # 100MB
    allowed-types: jpg,jpeg,png,gif,bmp,pdf,doc,docx,xls,xlsx,ppt,pptx,txt,zip,rar,7z,mp3,mp4,avi,mov,fbx,obj,3ds,max,blend

# ????
cors:
  allowed-origins: http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# ??????
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized